apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask
  labels:
    app.kubernetes.io/name: flask
    app.kubernetes.io/component: web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: flask
      app.kubernetes.io/component: web-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: flask
        app.kubernetes.io/component: web-app
    spec:
      containers:
      - name: flask
        image: ghcr.io/artikson/sample-site-flask
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
      imagePullSecrets:
      - name: github-auth