name: cicd

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: clone repo to build container
      uses: actions/checkout@v1

    - name: executing remote ssh commands to set env
      uses: artikson/sample-site@main
      with:
        script: |
          export POSTGRES_USER=${{ secrets.POSTGRES_USER }}

    - name: print secret
      run: echo $POSTGRES_USER
