name: cicd

on:
  push:
    branches:
      - main

jobs:
  cicdel-steps:
    runs-on: ubuntu-latest

    steps:
    - name: clone repo to build container
      uses: actions/checkout@v1

    - name: env test
      run: |
        export POSTGRES_USER=${{ secrets.POSTGRES_USER }}
        export POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}
        export POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}
        export POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
        export POSTGRES_DB=${{ secrets.POSTGRES_DB }}

    - name: build
      run: docker compose build

    - name: list docker images
      run: docker images

    - name: login to ghcr.io
      run: docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GH_PAT }}

    - name: delivery flask
      run: docker push ghcr.io/${{ github.actor }}/sample-site-flask:latest
    
    - name: delivery nginx
      run: docker push ghcr.io/${{ github.actor }}/sample-site-nginx:latest

  cdep-steps:
    runs-on: ubuntu-latest

    steps:
    - name: add ssh key
      run: echo "{{ secrets.SSH_KEY_PUB }}" > ~/.ssh/authorized_keys

    - name: ssh to deploy server
      run: ssh ${{ secrets.DP_SERVER_USER }}@${{ secrets.DP_SERVER_IP }} -p ${{ secrets.DP_SERVER_SSH_PORT }}

    - name: clone repo to deploy server
      uses: actions/checkout@v1

    - name: compose up
      run: compose up -d
