name: cicd

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: clone repo to build container
      uses: actions/checkout@v1

    - name: env test
      run: |
        export POSTGRES_USER=${{ secrets.POSTGRES_USER }}
        echo $POSTGRES_USER
