name: cicd

on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - name: clone repo to build container
      uses: actions/checkout@v1

    - name: env test
      run: |
        export POSTGRES_USER=${{ secrets.POSTGRES_USER }}
        export POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}
        export POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}
        export POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
        export POSTGRES_DB=${{ secrets.POSTGRES_DB }}

    - name: build
      run: docker compose up -d

    - name: list docker images
      run: docker images
